# theme: jekyll-theme-minimal
name: Hari Ilangovan

title: Hi! I'm Hari Ilangovan
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hari Ilangovan # add your name
author-img: hari-ilangovan.png # add your photo
about-author: I am an MS Analytics Candidate at Georgia Tech. <br /> <br /> I have a passion for data science, sports, and digital art. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: LifeOfHi # add your Github handle
social-linkedin: hari-ilangovan # add your Linkedin handle
social-email: hilangovan3@gatech.edu # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

# plugins:
#   - jekyll-sitemap
#   - jekyll-paginate
#   - jemoji

# paginate: 8
# paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
