collections:
  portfolio:
    output: true

title: Hari Ilangovan
description:  Where I post updates and maintain my portfolio
url: lifeofhi.github.io
# baseurl: /lifeofhi.github.io
author: Hari Ilangovan
linkedin: https://www.linkedin.com/in/hari-ilangovan/
github: https://github.com/LifeOfHi

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag